export const SET_SELECTED_SEAT = 'SET_SELECTED_SEAT';
export const SET_RESERVED_SEATS = 'SET_RESERVED_SEATS';
export const SET_CONFIRMED_SEAT = 'SET_CONFIRMED_SEAT';
export const SET_ERROR_SEAT = 'SET_ERROR_SEAT';
export const SET_SEATS = 'SET_SEATS';
